### ISSUE TITLE
[🔧] A likely mod incompatibility

### ISSUE THREAD

**Issue by TsplayerT** [TheDeathlyCow/thermoo#14]
### Playing Minecraft on version 1.20.1, using Modloader **Fabric** (0.15.10) is generating infinite error logs, with the message below:

```
[Render thread/INFO]: Manager is null
```

### The mods I'm using are these:

```
- Cloth Config API (11.1.118)
- Eldritch Mobs (1.15.1)
- Fabric API (0.92.1)
- Mouse Wheelie (1.13.0)
- Thermoo (2.3)
```
### below is the error log:
[latest.log](https://github.com/TheDeathlyCow/thermoo/files/15069310/latest.log)

**Comment by TheDeathlyCow** [comment]
Ok this is very weird. This log spam only occurs when Mouse Wheelie *and* Eldritch Mobs are installed (but not either separately), and only after joining a game and then exiting. I'm not sure why that is happening, but since it's not crashing I might just remove the log.

**Comment by TheDeathlyCow** [comment]
Also, the log is coming from the item attribute modifier API, when the fabric event `ModifyItemAttributeModifiersCallback` is called, so that indicates that for some reason one of those mods seems to be trying to access item attributes from the main menu.
