### ISSUE TITLE
Crash during gameplay

### ISSUE THREAD

**Issue by ChromaPIE** [TheDeathlyCow/thermoo#17]
Crash report: https://mclo.gs/EfGC6x8
Fabric 1.20.1

**Comment by TheDeathlyCow** [comment]
This is an issue in the Tinker's Construct "star" library. See Alpha-s-Stuff/TinkersConstruct#98. For some reason, I don't think star has been updated in Tinker's Construct yet, but you should be able to fix the issue by placing the prebuilt jar from the replies of that issue into your mods folder.
