### ISSUE TITLE
[ Issue ] Can't change players' temperature -- Always 0 or -1

### ISSUE THREAD

**Issue by ktg5** [TheDeathlyCow/thermoo#6]
Unsure if this is the correct repo to put this issue on, but I recently moved all the mods & world data that a friend & I were playing on when using Essential. When I set everything up for moving to my server, my friend seemed to be always freezing. No matter the commands I used (`/thermoo temperature [get|remove|add|set]`), it still won't budge.
Any help would be greatly appreciated.

**Comment by TheDeathlyCow** [comment]
Hi, are you using any other mods or datapacks that utilise with Thermoo, like Frostiful? If the temperature is always 0 or -1 then it seems like there may not be min or max temperature set.

**Comment by ktg5** [comment]
We do use Frostiful on server, probably should've mentioned that.

**Comment by TheDeathlyCow** [comment]
Ok, could you post a log then? I'd just like to see what mods you're using and versions.

**Comment by ktg5** [comment]
Yeah sure, I've uploaded it to a Gist: https://gist.github.com/ktg5/4e5e8b38edc6ef98df8dfeb95bacd291
Also I should've mentioned, this issue wasn't happening when running the world on Essential which is very strange to me.

**Comment by TheDeathlyCow** [comment]
Ok everything looks normal. Is your friend actually experiencing any freezing effects (eg weakeness, slowness, damage) or seeing anything on their HUD that suggests they should be frozen (cold hearts or the freezing border). I think the ticking logic will just keep the player at 0 or -1 temperature whenever they're in a cold environment, regardless of whether or not they have set up appropriate warming such as torch light.

**Comment by ktg5** [comment]
The only thing we noticed is that his screen would shake; no freezing hearts or slowness.

**Comment by TheDeathlyCow** [comment]
Frostiful only shakes the hand, not the screen. You can disable the shaking in the client config and see if the issue persists. Otherwise, it's likely not from Frostiful/Thermoo.
