### ISSUE TITLE
[Incompat] Armor Points ++ makes freezing hearts not render.

### ISSUE THREAD

**Issue by N0aW** [TheDeathlyCow/thermoo#9]
[Armor Points ++](https://github.com/Cheos137/ArmorpointsPlusplus) is a mod that changes the color of the health bar depending on your health. (If it's over 20)

It allows freezing hearts to be rendered either as normal, an overlay or an icon.

None of these work with Frostiful freezing.

**Comment by TheDeathlyCow** [comment]
Ran into an issue when trying to implement this where AP++ has a conflict with Yarn. 

I got this from Nerjal on Discord, will implement at some point soon: 

> So that's how you define a renaming -- here, renaming yarn's ClickableWidgen#method_48579 to displayButton (whatever the base Yarn name is, it conflicted with Create)
https://github.com/RecraftorsMC/Configured-Burn/blob/main/mappings/yarn-custom.tiny
And that's how you define the use of these remapping files
https://github.com/RecraftorsMC/Configured-Burn/blob/bd0ef0271b10a53e14462b15d6a17983f40b0a6b/build.gradle#L19
